version: "1"
services:
  - type: web
    name: GIEL
    runtime: DOCKER
    repo: https://github.com/i-tct/tct
    plan: FREE
    region: KAMPALA 
    dockerContext: .
    dockerfilePath: ./DOCKER FILE
    autoDeployTrigger: COMMIT

    envVars:
      # Compulsory: must be set manually
      - key: SESSION ID
        sync: false

      - key: TIME/ZONE
        sync: false

      - key: PREFIX
        sync: false

      - key: DASHBOARD_USER
        sync: false

      - key: DASHBOARD_PASS
        sync: false

      - key: SERVER_PORT
        value: "3010"
