version: "1"
services:
  - type: web
    name: tct
    runtime: docker
    repo: https://github.com/i-tct/tct
    plan: free
    region: virginia
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit

    envVars:
      # Compulsory: must be set manually
      - key: SESSION ID
        sync: false

      - key: TIME/ZONE
        sync: false

      - key: PREFIX
        sync: false

      - key: DASHBOARD_USER
        sync: false

      - key: DASHBOARD_PASS
        sync: false

      - key: server_port
        value: "3010"
