version: "1"
services:
  - type: web
    name: tct
    runtime: docker
    repo: https://github.com/i-tct/tct
    plan: free
    region: virginia
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit

    envVars:
      # Compulsory: must be set manually
      - key: tct_ba480c4
        sync: false

      - key: Uganda 
        sync: false

      - key: .
        sync: false

      - key: Collins 
        sync: false

      - key: colls
        sync: false

      - key: server_port
        value: "3010"
